version: '3'
services:
  pgadmin4:
    image: dpage/pgadmin4:8.3
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=your@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGID=100
      - PUID=1003
    volumes:
      - /share/dockerapps/databases/pgadmin4:/var/lib/pgadmin
    networks:
      - databasenetwork

networks:
  databasenetwork:
    driver: bridge